<a href="https://colab.research.google.com/github/tarannump096-cpu/NLP/blob/main/NLP1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("/content/nlp_preprocessing_dataset.csv")

In [ ]:
df

    id                                               text
0    1  I LOVE NLP!!! 😍 Visit https://nlp.com for more...
1    2  <p>This is a HTML paragraph about NLP</p>   It...
2    3  Python is awsome for AI!!! Check https://pytho...
3    4  I realy like studying NLP 😊😊 It is sooo intere...
4    5  <div>Machine learning is powerfull</div> Learn...
5    6  Text preprocessing includes tokenization, stem...
6    7  This sentence has spelling erors and     too m...
7    8   Hello!!! How are you??? I'm learning NLP today 😃
8    9  Visit our WEBSITE at https://datascience.com f...
9   10  <h1>NLP Heading</h1> This text has HTML tags a...
10  11  I like Python programming...but sometimes it i...
11  12                    AI and NLP are the FUTURE!!! 🚀🚀
12  13  This line contains newline\nSee next line of t...
13  14            Too      many       spaces      here!!!
14  15  NLP preprocessing removes HTML, URLs, emojis 😊...
15  16  I LOOOVE data science!!! Visit https://datasci...
16  17  <b>Bold HTML text</b> with some random punctua...
17  18       Machine learning is amazng and very usefull.
18  19     Chatbots use NLP and AI to talk with humans!!!
19  20  Check this website https://ai-example.com for ...
20  21                  I realy enjoy coding in PYTHON!!!
21  22    <div>HTML content here</div> Learn NLP today!!!
22  23    Deep learning models work well with BIG DATA!!!
23  24        Spelling mistake exampple in this sentence.
24  25  Remove URLs like https://google.com and http:/...
25  26  I am HAPPY 😊 learning Natural Language Process...
26  27  Extra     spaces      everywhere      in     t...
27  28  HTML tags like <p>, <div>, <h1> should be remo...
28  29      Visit www.example.com for more INFORMATION!!!
29  30                AI is the FUTURE of TECHNOLOGY!!! 🚀
30  31         Python programming is funnn and powerfull.
31  32  This line has newline character\nSecond line h...
32  33  Check this link https://openai.com for AI rese...
33  34               I LOVE machine learning and NLP!!! 😍
34  35            Text preprocessing cleans messy data!!!
35  36                      Too much punctuation!!!???!!!
36  37    Some HTML <span>inline tags</span> appear here.
37  38         Speling mistakes are commmon in text data.
38  39             Remove emoji 😊😂👍 during preprocessing.
39  40  Sentence with UPPERCASE WORDS and lowercase wo...
40  41        Extra spaces should    be cleaned properly.
41  42         Visit https://nlp-course.com to learn NLP.
42  43        I realy realy like AI and machine learning.
43  44  <p>Paragraph HTML</p> with link https://exampl...
44  45       Numbers also appear 123 in some sentences!!!
45  46      Sentence with emoji 😃 and URL https://test.ai
46  47           Newline example\nAnother sentence below.
47  48         Data SCIENCE and AI are trending fields!!!
48  49      Preprocessing removes noise from TEXT DATA!!!
49  50   Final sentence with HTML <b>bold</b> and emoji 😊

In [ ]:
df["text"]=df["text"].str.lower()

In [ ]:
df

    id                                               text
0    1  i love nlp!!! 😍 visit https://nlp.com for more...
1    2  <p>this is a html paragraph about nlp</p>   it...
2    3  python is awsome for ai!!! check https://pytho...
3    4  i realy like studying nlp 😊😊 it is sooo intere...
4    5  <div>machine learning is powerfull</div> learn...
5    6  text preprocessing includes tokenization, stem...
6    7  this sentence has spelling erors and     too m...
7    8   hello!!! how are you??? i'm learning nlp today 😃
8    9  visit our website at https://datascience.com f...
9   10  <h1>nlp heading</h1> this text has html tags a...
10  11  i like python programming...but sometimes it i...
11  12                    ai and nlp are the future!!! 🚀🚀
12  13  this line contains newline\nsee next line of t...
13  14            too      many       spaces      here!!!
14  15  nlp preprocessing removes html, urls, emojis 😊...
15  16  i looove data science!!! visit https://datasci...
16  17  <b>bold html text</b> with some random punctua...
17  18       machine learning is amazng and very usefull.
18  19     chatbots use nlp and ai to talk with humans!!!
19  20  check this website https://ai-example.com for ...
20  21                  i realy enjoy coding in python!!!
21  22    <div>html content here</div> learn nlp today!!!
22  23    deep learning models work well with big data!!!
23  24        spelling mistake exampple in this sentence.
24  25  remove urls like https://google.com and http:/...
25  26  i am happy 😊 learning natural language process...
26  27  extra     spaces      everywhere      in     t...
27  28  html tags like <p>, <div>, <h1> should be remo...
28  29      visit www.example.com for more information!!!
29  30                ai is the future of technology!!! 🚀
30  31         python programming is funnn and powerfull.
31  32  this line has newline character\nsecond line h...
32  33  check this link https://openai.com for ai rese...
33  34               i love machine learning and nlp!!! 😍
34  35            text preprocessing cleans messy data!!!
35  36                      too much punctuation!!!???!!!
36  37    some html <span>inline tags</span> appear here.
37  38         speling mistakes are commmon in text data.
38  39             remove emoji 😊😂👍 during preprocessing.
39  40  sentence with uppercase words and lowercase wo...
40  41        extra spaces should    be cleaned properly.
41  42         visit https://nlp-course.com to learn nlp.
42  43        i realy realy like ai and machine learning.
43  44  <p>paragraph html</p> with link https://exampl...
44  45       numbers also appear 123 in some sentences!!!
45  46      sentence with emoji 😃 and url https://test.ai
46  47           newline example\nanother sentence below.
47  48         data science and ai are trending fields!!!
48  49      preprocessing removes noise from text data!!!
49  50   final sentence with html <b>bold</b> and emoji 😊

In [ ]:
import re

In [ ]:
def remove_html_tags(text):
  pattern="<.*?>"
  clean_text=re.sub(pattern, "", text)
  return clean_text

In [ ]:
df["new_text"]=df["text"].apply(remove_html_tags)

In [ ]:
df

,id,text,new_text
0,1,i love nlp!!! 😍 visit https://nlp.com for more...,i love nlp!!! 😍 visit https://nlp.com for more...
1,2,<p>this is a html paragraph about nlp</p> it...,this is a html paragraph about nlp it has ex...
2,3,python is awsome for ai!!! check https://pytho...,python is awsome for ai!!! check https://pytho...
3,4,i realy like studying nlp 😊😊 it is sooo intere...,i realy like studying nlp 😊😊 it is sooo intere...
4,5,<div>machine learning is powerfull</div> learn...,machine learning is powerfull learn at https:/...
5,6,"text preprocessing includes tokenization, stem...","text preprocessing includes tokenization, stem..."
6,7,this sentence has spelling erors and too m...,this sentence has spelling erors and too m...
7,8,hello!!! how are you??? i'm learning nlp today 😃,hello!!! how are you??? i'm learning nlp today 😃
8,9,visit our website at https://datascience.com f...,visit our website at https://datascience.com f...
9,10,<h1>nlp heading</h1> this text has html tags a...,nlp heading this text has html tags and url ht...
10,11,i like python programming...but sometimes it i...,i like python programming...but sometimes it i...
11,12,ai and nlp are the future!!! 🚀🚀,ai and nlp are the future!!! 🚀🚀
12,13,this line contains newline\nsee next line of t...,this line contains newline\nsee next line of t...
13,14,too many spaces here!!!,too many spaces here!!!
14,15,"nlp preprocessing removes html, urls, emojis 😊...","nlp preprocessing removes html, urls, emojis 😊..."
15,16,i looove data science!!! visit https://datasci...,i looove data science!!! visit https://datasci...
16,17,<b>bold html text</b> with some random punctua...,bold html text with some random punctuation!!!
17,18,machine learning is amazng and very usefull.,machine learning is amazng and very usefull.
18,19,chatbots use nlp and ai to talk with humans!!!,chatbots use nlp and ai to talk with humans!!!
19,20,check this website https://ai-example.com for ...,check this website https://ai-example.com for ...
20,21,i realy enjoy coding in python!!!,i realy enjoy coding in python!!!
21,22,<div>html content here</div> learn nlp today!!!,html content here learn nlp today!!!
22,23,deep learning models work well with big data!!!,deep learning models work well with big data!!!
23,24,spelling mistake exampple in this sentence.,spelling mistake exampple in this sentence.
24,25,remove urls like https://google.com and http:/...,remove urls like https://google.com and http:/...
25,26,i am happy 😊 learning natural language process...,i am happy 😊 learning natural language process...
26,27,extra spaces everywhere in t...,extra spaces everywhere in t...
27,28,"html tags like <p>, <div>, <h1> should be remo...","html tags like , , should be removed."
28,29,visit www.example.com for more information!!!,visit www.example.com for more information!!!
29,30,ai is the future of technology!!! 🚀,ai is the future of technology!!! 🚀
30,31,python programming is funnn and powerfull.,python programming is funnn and powerfull.
31,32,this line has newline character\nsecond line h...,this line has newline character\nsecond line h...
32,33,check this link https://openai.com for ai rese...,check this link https://openai.com for ai rese...
33,34,i love machine learning and nlp!!! 😍,i love machine learning and nlp!!! 😍
34,35,text preprocessing cleans messy data!!!,text preprocessing cleans messy data!!!
35,36,too much punctuation!!!???!!!,too much punctuation!!!???!!!
36,37,some html <span>inline tags</span> appear here.,some html inline tags appear here.
37,38,speling mistakes are commmon in text data.,speling mistakes are commmon in text data.
38,39,remove emoji 😊😂👍 during preprocessing.,remove emoji 😊😂👍 during preprocessing.
39,40,sentence with uppercase words and lowercase wo...,sentence with uppercase words and lowercase wo...
40,41,extra spaces should be cleaned properly.,extra spaces should be cleaned properly.
41,42,visit https://nlp-course.com to learn nlp.,visit https://nlp-course.com to learn nlp.
42,43,i realy realy like ai and machine learning.,i realy realy like ai and machine learning.
43,44,<p>paragraph html</p> with link https://exampl...,paragraph html with link https://example.org
44,45,numbers also appear 123 in some sentences!!!,numbers also appear 123 in some sentences!!!
45,46,sentence with emoji 😃 and url https://test.ai,sentence with emoji 😃 and url https://test.ai
46,47,newline example\nanother sentence below.,newline example\nanother sentence below.
47,48,data science and ai are trending fields!!!,data science and ai are trending fields!!!
48,49,preprocessing removes noise from text data!!!,preprocessing removes noise from text data!!!
49,50,final sentence with html <b>bold</b> and emoji 😊,final sentence with html bold and emoji 😊

In [ ]:
def removal_url(text):
    pattern="https?://\S+|www\.\S+"
    clean_text=re.sub(pattern,"",text)
    return clean_text

<>:2: SyntaxWarning: invalid escape sequence '\S'
<>:2: SyntaxWarning: invalid escape sequence '\S'
/tmp/ipykernel_6979/1894047134.py:2: SyntaxWarning: invalid escape sequence '\S'
  pattern="https?://\S+|www\.\S+"

In [ ]:
df["new_text"]=df["new_text"].apply(removal_url)

In [ ]:
df

,id,text,new_text
0,1,i love nlp!!! 😍 visit https://nlp.com for more...,i love nlp!!! 😍 visit for more info.
1,2,<p>this is a html paragraph about nlp</p> it...,this is a html paragraph about nlp it has ex...
2,3,python is awsome for ai!!! check https://pytho...,python is awsome for ai!!! check
3,4,i realy like studying nlp 😊😊 it is sooo intere...,i realy like studying nlp 😊😊 it is sooo intere...
4,5,<div>machine learning is powerfull</div> learn...,machine learning is powerfull learn at
5,6,"text preprocessing includes tokenization, stem...","text preprocessing includes tokenization, stem..."
6,7,this sentence has spelling erors and too m...,this sentence has spelling erors and too m...
7,8,hello!!! how are you??? i'm learning nlp today 😃,hello!!! how are you??? i'm learning nlp today 😃
8,9,visit our website at https://datascience.com f...,visit our website at for data science tutorials.
9,10,<h1>nlp heading</h1> this text has html tags a...,nlp heading this text has html tags and url
10,11,i like python programming...but sometimes it i...,i like python programming...but sometimes it i...
11,12,ai and nlp are the future!!! 🚀🚀,ai and nlp are the future!!! 🚀🚀
12,13,this line contains newline\nsee next line of t...,this line contains newline\nsee next line of t...
13,14,too many spaces here!!!,too many spaces here!!!
14,15,"nlp preprocessing removes html, urls, emojis 😊...","nlp preprocessing removes html, urls, emojis 😊..."
15,16,i looove data science!!! visit https://datasci...,i looove data science!!! visit
16,17,<b>bold html text</b> with some random punctua...,bold html text with some random punctuation!!!
17,18,machine learning is amazng and very usefull.,machine learning is amazng and very usefull.
18,19,chatbots use nlp and ai to talk with humans!!!,chatbots use nlp and ai to talk with humans!!!
19,20,check this website https://ai-example.com for ...,check this website for ai news.
20,21,i realy enjoy coding in python!!!,i realy enjoy coding in python!!!
21,22,<div>html content here</div> learn nlp today!!!,html content here learn nlp today!!!
22,23,deep learning models work well with big data!!!,deep learning models work well with big data!!!
23,24,spelling mistake exampple in this sentence.,spelling mistake exampple in this sentence.
24,25,remove urls like https://google.com and http:/...,remove urls like and
25,26,i am happy 😊 learning natural language process...,i am happy 😊 learning natural language process...
26,27,extra spaces everywhere in t...,extra spaces everywhere in t...
27,28,"html tags like <p>, <div>, <h1> should be remo...","html tags like , , should be removed."
28,29,visit www.example.com for more information!!!,visit for more information!!!
29,30,ai is the future of technology!!! 🚀,ai is the future of technology!!! 🚀
30,31,python programming is funnn and powerfull.,python programming is funnn and powerfull.
31,32,this line has newline character\nsecond line h...,this line has newline character\nsecond line h...
32,33,check this link https://openai.com for ai rese...,check this link for ai research.
33,34,i love machine learning and nlp!!! 😍,i love machine learning and nlp!!! 😍
34,35,text preprocessing cleans messy data!!!,text preprocessing cleans messy data!!!
35,36,too much punctuation!!!???!!!,too much punctuation!!!???!!!
36,37,some html <span>inline tags</span> appear here.,some html inline tags appear here.
37,38,speling mistakes are commmon in text data.,speling mistakes are commmon in text data.
38,39,remove emoji 😊😂👍 during preprocessing.,remove emoji 😊😂👍 during preprocessing.
39,40,sentence with uppercase words and lowercase wo...,sentence with uppercase words and lowercase wo...
40,41,extra spaces should be cleaned properly.,extra spaces should be cleaned properly.
41,42,visit https://nlp-course.com to learn nlp.,visit to learn nlp.
42,43,i realy realy like ai and machine learning.,i realy realy like ai and machine learning.
43,44,<p>paragraph html</p> with link https://exampl...,paragraph html with link
44,45,numbers also appear 123 in some sentences!!!,numbers also appear 123 in some sentences!!!
45,46,sentence with emoji 😃 and url https://test.ai,sentence with emoji 😃 and url
46,47,newline example\nanother sentence below.,newline example\nanother sentence below.
47,48,data science and ai are trending fields!!!,data science and ai are trending fields!!!
48,49,preprocessing removes noise from text data!!!,preprocessing removes noise from text data!!!
49,50,final sentence with html <b>bold</b> and emoji 😊,final sentence with html bold and emoji 😊

In [ ]:
def remove_newline(text):
    pattern="\n"
    clean_text=re.sub(pattern,"",text)
    return clean_text

In [ ]:
df["new_text"]=df["new_text"].apply(remove_newline)

In [ ]:
df

,id,text,new_text
0,1,i love nlp!!! 😍 visit https://nlp.com for more...,i love nlp!!! 😍 visit for more info.
1,2,<p>this is a html paragraph about nlp</p> it...,this is a html paragraph about nlp it has ex...
2,3,python is awsome for ai!!! check https://pytho...,python is awsome for ai!!! check
3,4,i realy like studying nlp 😊😊 it is sooo intere...,i realy like studying nlp 😊😊 it is sooo intere...
4,5,<div>machine learning is powerfull</div> learn...,machine learning is powerfull learn at
5,6,"text preprocessing includes tokenization, stem...","text preprocessing includes tokenization, stem..."
6,7,this sentence has spelling erors and too m...,this sentence has spelling erors and too m...
7,8,hello!!! how are you??? i'm learning nlp today 😃,hello!!! how are you??? i'm learning nlp today 😃
8,9,visit our website at https://datascience.com f...,visit our website at for data science tutorials.
9,10,<h1>nlp heading</h1> this text has html tags a...,nlp heading this text has html tags and url
10,11,i like python programming...but sometimes it i...,i like python programming...but sometimes it i...
11,12,ai and nlp are the future!!! 🚀🚀,ai and nlp are the future!!! 🚀🚀
12,13,this line contains newline\nsee next line of t...,this line contains newlinesee next line of text.
13,14,too many spaces here!!!,too many spaces here!!!
14,15,"nlp preprocessing removes html, urls, emojis 😊...","nlp preprocessing removes html, urls, emojis 😊..."
15,16,i looove data science!!! visit https://datasci...,i looove data science!!! visit
16,17,<b>bold html text</b> with some random punctua...,bold html text with some random punctuation!!!
17,18,machine learning is amazng and very usefull.,machine learning is amazng and very usefull.
18,19,chatbots use nlp and ai to talk with humans!!!,chatbots use nlp and ai to talk with humans!!!
19,20,check this website https://ai-example.com for ...,check this website for ai news.
20,21,i realy enjoy coding in python!!!,i realy enjoy coding in python!!!
21,22,<div>html content here</div> learn nlp today!!!,html content here learn nlp today!!!
22,23,deep learning models work well with big data!!!,deep learning models work well with big data!!!
23,24,spelling mistake exampple in this sentence.,spelling mistake exampple in this sentence.
24,25,remove urls like https://google.com and http:/...,remove urls like and
25,26,i am happy 😊 learning natural language process...,i am happy 😊 learning natural language process...
26,27,extra spaces everywhere in t...,extra spaces everywhere in t...
27,28,"html tags like <p>, <div>, <h1> should be remo...","html tags like , , should be removed."
28,29,visit www.example.com for more information!!!,visit for more information!!!
29,30,ai is the future of technology!!! 🚀,ai is the future of technology!!! 🚀
30,31,python programming is funnn and powerfull.,python programming is funnn and powerfull.
31,32,this line has newline character\nsecond line h...,this line has newline charactersecond line here.
32,33,check this link https://openai.com for ai rese...,check this link for ai research.
33,34,i love machine learning and nlp!!! 😍,i love machine learning and nlp!!! 😍
34,35,text preprocessing cleans messy data!!!,text preprocessing cleans messy data!!!
35,36,too much punctuation!!!???!!!,too much punctuation!!!???!!!
36,37,some html <span>inline tags</span> appear here.,some html inline tags appear here.
37,38,speling mistakes are commmon in text data.,speling mistakes are commmon in text data.
38,39,remove emoji 😊😂👍 during preprocessing.,remove emoji 😊😂👍 during preprocessing.
39,40,sentence with uppercase words and lowercase wo...,sentence with uppercase words and lowercase wo...
40,41,extra spaces should be cleaned properly.,extra spaces should be cleaned properly.
41,42,visit https://nlp-course.com to learn nlp.,visit to learn nlp.
42,43,i realy realy like ai and machine learning.,i realy realy like ai and machine learning.
43,44,<p>paragraph html</p> with link https://exampl...,paragraph html with link
44,45,numbers also appear 123 in some sentences!!!,numbers also appear 123 in some sentences!!!
45,46,sentence with emoji 😃 and url https://test.ai,sentence with emoji 😃 and url
46,47,newline example\nanother sentence below.,newline exampleanother sentence below.
47,48,data science and ai are trending fields!!!,data science and ai are trending fields!!!
48,49,preprocessing removes noise from text data!!!,preprocessing removes noise from text data!!!
49,50,final sentence with html <b>bold</b> and emoji 😊,final sentence with html bold and emoji 😊

In [ ]:
import string

In [ ]:
exclude=list(string.punctuation)

In [ ]:
exclude

['!',
 '"',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '/',
 ':',
 ';',
 '<',
 '=',
 '>',
 '?',
 '@',
 '[',
 '\\',
 ']',
 '^',
 '_',
 '`',
 '{',
 '|',
 '}',
 '~']

In [ ]:
def remove_punctuation(text):
    # This pattern matches one or more occurrences of any character in string.punctuation
    # re.escape is used to escape any special regex characters within string.punctuation
    punctuation_pattern = r'[' + re.escape(string.punctuation) + r']+'
    clean_text = re.sub(punctuation_pattern, "", text)
    return clean_text

In [ ]:
df["new_text"]=df["new_text"].apply(remove_punctuation)

In [ ]:
df

,id,text,new_text
0,1,i love nlp!!! 😍 visit https://nlp.com for more...,i love nlp 😍 visit for more info
1,2,<p>this is a html paragraph about nlp</p> it...,this is a html paragraph about nlp it has ex...
2,3,python is awsome for ai!!! check https://pytho...,python is awsome for ai check
3,4,i realy like studying nlp 😊😊 it is sooo intere...,i realy like studying nlp 😊😊 it is sooo intere...
4,5,<div>machine learning is powerfull</div> learn...,machine learning is powerfull learn at
5,6,"text preprocessing includes tokenization, stem...",text preprocessing includes tokenization stemm...
6,7,this sentence has spelling erors and too m...,this sentence has spelling erors and too m...
7,8,hello!!! how are you??? i'm learning nlp today 😃,hello how are you im learning nlp today 😃
8,9,visit our website at https://datascience.com f...,visit our website at for data science tutorials
9,10,<h1>nlp heading</h1> this text has html tags a...,nlp heading this text has html tags and url
10,11,i like python programming...but sometimes it i...,i like python programmingbut sometimes it is c...
11,12,ai and nlp are the future!!! 🚀🚀,ai and nlp are the future 🚀🚀
12,13,this line contains newline\nsee next line of t...,this line contains newlinesee next line of text
13,14,too many spaces here!!!,too many spaces here
14,15,"nlp preprocessing removes html, urls, emojis 😊...",nlp preprocessing removes html urls emojis 😊 a...
15,16,i looove data science!!! visit https://datasci...,i looove data science visit
16,17,<b>bold html text</b> with some random punctua...,bold html text with some random punctuation
17,18,machine learning is amazng and very usefull.,machine learning is amazng and very usefull
18,19,chatbots use nlp and ai to talk with humans!!!,chatbots use nlp and ai to talk with humans
19,20,check this website https://ai-example.com for ...,check this website for ai news
20,21,i realy enjoy coding in python!!!,i realy enjoy coding in python
21,22,<div>html content here</div> learn nlp today!!!,html content here learn nlp today
22,23,deep learning models work well with big data!!!,deep learning models work well with big data
23,24,spelling mistake exampple in this sentence.,spelling mistake exampple in this sentence
24,25,remove urls like https://google.com and http:/...,remove urls like and
25,26,i am happy 😊 learning natural language process...,i am happy 😊 learning natural language processing
26,27,extra spaces everywhere in t...,extra spaces everywhere in t...
27,28,"html tags like <p>, <div>, <h1> should be remo...",html tags like should be removed
28,29,visit www.example.com for more information!!!,visit for more information
29,30,ai is the future of technology!!! 🚀,ai is the future of technology 🚀
30,31,python programming is funnn and powerfull.,python programming is funnn and powerfull
31,32,this line has newline character\nsecond line h...,this line has newline charactersecond line here
32,33,check this link https://openai.com for ai rese...,check this link for ai research
33,34,i love machine learning and nlp!!! 😍,i love machine learning and nlp 😍
34,35,text preprocessing cleans messy data!!!,text preprocessing cleans messy data
35,36,too much punctuation!!!???!!!,too much punctuation
36,37,some html <span>inline tags</span> appear here.,some html inline tags appear here
37,38,speling mistakes are commmon in text data.,speling mistakes are commmon in text data
38,39,remove emoji 😊😂👍 during preprocessing.,remove emoji 😊😂👍 during preprocessing
39,40,sentence with uppercase words and lowercase wo...,sentence with uppercase words and lowercase words
40,41,extra spaces should be cleaned properly.,extra spaces should be cleaned properly
41,42,visit https://nlp-course.com to learn nlp.,visit to learn nlp
42,43,i realy realy like ai and machine learning.,i realy realy like ai and machine learning
43,44,<p>paragraph html</p> with link https://exampl...,paragraph html with link
44,45,numbers also appear 123 in some sentences!!!,numbers also appear 123 in some sentences
45,46,sentence with emoji 😃 and url https://test.ai,sentence with emoji 😃 and url
46,47,newline example\nanother sentence below.,newline exampleanother sentence below
47,48,data science and ai are trending fields!!!,data science and ai are trending fields
48,49,preprocessing removes noise from text data!!!,preprocessing removes noise from text data
49,50,final sentence with html <b>bold</b> and emoji 😊,final sentence with html bold and emoji 😊