<a href="https://colab.research.google.com/github/tarannump096-cpu/NLP/blob/main/NLP3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install emoji

Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 10.2 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.15.0

In [ ]:
!pip install textblob

Requirement already satisfied: textblob in /usr/local/lib/python3.12/dist-packages (0.19.0)
Requirement already satisfied: nltk>=3.9 in /usr/local/lib/python3.12/dist-packages (from textblob) (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (8.3.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (4.67.3)

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("/content/noisy_email_spam_dataset.csv")

In [ ]:
df

   label                                         email_text
0   spam  Hot deal!!! buy followers!!! http://boost-soci...
1    ham         Hey,\nI think there is a typo in the file.
2   spam  <html><body>CONGRATS!!! u won $1000!!! click <...
3   spam               click fast!!!! http://prize-drop.win
4    ham         <br>Don't forget to submit the assignment.
5   spam  <div>last chance!!! 90% OFF!!! http://super-sa...
6   spam  OMG!!! unbelievable deal!!!! http://crazy-offe...
7   spam  limited time!!!! FREE gift card!!! http://gift...
8   spam  hey u!!! win iphone!!! go --> http://scamlink....
9   spam  Winner!!! send ur details ASAP!!! http://claim...
10   ham             Plz update the spreadsheet when u can.
11   ham         <p>attached the invoice... check once.</p>
12   ham         hey!!! r u coming to the party tonight?? 🎉
13  spam  Dear custmer,, update info here http://phish-l...
14  spam  cheap flights!!! book now http://flight-deals.biz
15  spam  CONGRATULATIONSSS!!!! you WON!!! <a href='http...
16  spam  earn 5000$ daily!!! work frm home!!! http://ea...
17   ham            Reminder: dentist appt tomorrow @ 10am.
18  spam     Special promo!!!! visit http://bit.ly/spamdeal
19   ham   <p>Please review the doc I shared yesterday.</p>
20   ham                   hey broooo!!! long time no see 😂
21  spam  <b>Get FREE bitcoin!!!</b> http://btc-airdrop....
22  spam     Get rich quick!!! http://get-rich-quick.biz 💰💰
23   ham                 Let's catch up sometime next week.
24  spam  urgent!!! ur account suspended!!! login http:/...
25   ham              <div>call me when u reach home.</div>
26   ham                 Reminder!!! team outing tomorrow 😄
27  spam  plzzz verify ur bank acct here http://bank-sec...
28  spam  Dear user,,, claim ur prize now!!! visit http:...
29   ham                   Don't forget mom's birthday!!! 🎂
30  spam  OMG!!! u r selected!!! claim reward 👉 http://r...
31  spam      Buy cheap meds now!!! http://meds-discount.ru
32   ham            hey,\nI'll send the slides later today.
33   ham           Hey there!! just testing newline\n\nhere
34   ham  Can u check this link http://example.com and c...
35  spam  <div>LIMITED offer!!! buy now @ http://cheap-d...
36  spam  <h1>FREE crypto giveaway!!!</h1> http://fakecr...
37   ham                 Plzz fix the bug in module 3 asap.
38  spam    <p>Earn $$$ from home!!! no skill needed!!!</p>
39   ham             Did u see the match yesterday??? wow!!
40  spam  verify ur paypal now http://secure-paypal-logi...
41   ham                      Good morning! coffee later? ☕
42   ham  Hi team,\nThe server restart worked... check a...
43   ham   <div>Meeting at 3pm today. don't be late!!</div>
44   ham             can u review my code??? it's messy lol
45   ham  Hey John,\nCan u send the report by today plz?...
46   ham                       Thanks for ur help earlier!!
47   ham                        Lunch @ 1pm?? let me know!!
48  spam  FREEE vacation!!! click here <br> http://holid...
49   ham                  Project deadline moved to Friday.

In [ ]:
df["email_text"]=df["email_text"].str.lower()

In [ ]:
df.head()

  label                                         email_text
0  spam  hot deal!!! buy followers!!! http://boost-soci...
1   ham         hey,\ni think there is a typo in the file.
2  spam  <html><body>congrats!!! u won $1000!!! click <...
3  spam               click fast!!!! http://prize-drop.win
4   ham         <br>don't forget to submit the assignment.

In [ ]:
import re
def removal_html_tags(text):
    pattern="<.*?>"
    clean_text=re.sub(pattern,"",text)
    return clean_text

In [ ]:
df["email_text"]=df["email_text"].apply(removal_html_tags)

In [ ]:
df.head()

  label                                         email_text
0  spam  hot deal!!! buy followers!!! http://boost-soci...
1   ham         hey,\ni think there is a typo in the file.
2  spam     congrats!!! u won $1000!!! click here now!!! 😱
3  spam               click fast!!!! http://prize-drop.win
4   ham             don't forget to submit the assignment.

In [ ]:
def removal_url(text):
    pattern="https?://\S+|www\.\S+"
    clean_text=re.sub(pattern,"",text)
    return clean_text

<>:2: SyntaxWarning: invalid escape sequence '\S'
<>:2: SyntaxWarning: invalid escape sequence '\S'
/tmp/ipykernel_9576/1894047134.py:2: SyntaxWarning: invalid escape sequence '\S'
  pattern="https?://\S+|www\.\S+"

In [ ]:
df["email_text"]=df["email_text"].apply(removal_url)

In [ ]:
df.head()

  label                                      email_text
0  spam                   hot deal!!! buy followers!!!
1   ham      hey,\ni think there is a typo in the file.
2  spam  congrats!!! u won $1000!!! click here now!!! 😱
3  spam                                 click fast!!!!
4   ham          don't forget to submit the assignment.

In [ ]:
import string

In [ ]:
exlcude=list(string.punctuation)

In [ ]:
exlcude

['!',
 '"',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '/',
 ':',
 ';',
 '<',
 '=',
 '>',
 '?',
 '@',
 '[',
 '\\',
 ']',
 '^',
 '_',
 '`',
 '{',
 '|',
 '}',
 '~']

In [ ]:
def remove_punctuations(text):
    for char in exlcude:
        if char in text:
            text=text.replace(char,"")
    return text

In [ ]:
df["email_text"]=df["email_text"].apply(remove_punctuations)

In [ ]:
df.head()

  label                                email_text
0  spam                   hot deal buy followers
1   ham  hey\ni think there is a typo in the file
2  spam      congrats u won 1000 click here now 😱
3  spam                               click fast
4   ham      dont forget to submit the assignment

In [ ]:
def remove_newline_character(text):
    pattern="\n"
    clean_text=re.sub(pattern,"",text)
    return clean_text

In [ ]:
df["email_text"]=df["email_text"].apply(remove_newline_character)

In [ ]:
df.head()

  label                              email_text
0  spam                 hot deal buy followers
1   ham  heyi think there is a typo in the file
2  spam    congrats u won 1000 click here now 😱
3  spam                             click fast
4   ham    dont forget to submit the assignment

In [ ]:
def remove_extra_space(text):
    pattern="\s+"
    clean_text=re.sub(pattern," ",text)
    return clean_text

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_9576/154834758.py:2: SyntaxWarning: invalid escape sequence '\s'
  pattern="\s+"

In [ ]:
df["email_text"]=df["email_text"].apply(remove_extra_space)

In [ ]:
df.head()

  label                              email_text
0  spam                 hot deal buy followers
1   ham  heyi think there is a typo in the file
2  spam    congrats u won 1000 click here now 😱
3  spam                             click fast
4   ham    dont forget to submit the assignment

In [ ]:
import emoji

In [ ]:
str1="😂"

In [ ]:
emoji.demojize(str1)

':face_with_tears_of_joy:'

In [ ]:
def handling_emojis(text):
    clean_text=emoji.demojize(text)
    return clean_text

In [ ]:
df["email_text"]=df["email_text"].apply(handling_emojis)

In [ ]:
df.head()

  label                                         email_text
0  spam                            hot deal buy followers
1   ham             heyi think there is a typo in the file
2  spam  congrats u won 1000 click here now :face_screa...
3  spam                                        click fast
4   ham               dont forget to submit the assignment

In [ ]:
def handling_extra_characters(text):
    text=text.replace(":"," ")
    text=text.replace("_"," ")
    return text

In [ ]:
df["email_text"]=df["email_text"].apply(handling_extra_characters)

In [ ]:
df.head()

In [ ]:
from textblob import TextBlob

In [ ]:
str2="ceeertain whaat happpppen?"

In [ ]:
blob=TextBlob(str2)

In [ ]:
str(blob.correct())

'certain what happpppen?'

In [ ]:
def correct_spelling(text):
    blob=TextBlob(text)
    clean_text=str(blob.correct())
    return clean_text

In [ ]:
df["email_text"]=df["email_text"].apply(correct_spelling)

In [ ]:
df.head()

  label                                         email_text
0  spam                            hot deal buy followers
1   ham              hey think there is a type in the file
2  spam  congress u won 1000 click here now  face screa...
3  spam                                        click fast
4   ham               dont forget to submit the assignment

In [ ]:
df

   label                                         email_text
0   spam                            hot deal buy followers
1    ham              hey think there is a type in the file
2   spam  congress u won 1000 click here now  face screa...
3   spam                                        click fast
4    ham               dont forget to submit the assignment
5   spam                                last chance 90 off
6   spam                             org unbelievable deal
7   spam                       limited time free gift card
8   spam                  hey u win phone go  mobile phone
9   spam                        winner send or details sap
10   ham              ply update the spreadsheet when u can
11   ham                      attached the voice check once
12   ham  hey r u coming to the party tonight  party cop...
13  spam                    dear customer update into here
14  spam                            cheap flights book now
15  spam                      congratulations you won claim
16  spam                    earn 5000 daily work from home
17   ham                   reminder dentist apt tomorrow am
18  spam                               special promo visit
19   ham            please review the do i shared yesterday
20   ham  hey brook long time no see  face with tears of...
21  spam                                  get free bitcoin
22  spam              get rich quick  money bag  money bag
23   ham                   lets catch up sometime next week
24  spam                 urgent or account suspended login
25   ham                          call me when u reach home
26   ham  reminder team outing tomorrow  grinning face w...
27  spam                     plzzz verify or bank act here
28  spam                dear user claim or prize now visit
29   ham          dont forget moss birthday  birthday cake
30  spam  org u r selected claim reward  backward index ...
31  spam                                buy cheap beds now
32   ham                    hill send the sides later today
33   ham                 hey there just testing newlinehere
34   ham                  can u check this link and confirm
35  spam                             limited offer buy now
36  spam                               free crept giveaway
37   ham                   plan fix the bug in module 3 sap
38  spam                     earn from home no skill needed
39   ham                  did u see the match yesterday now
40  spam                               verify or papal now
41   ham           good morning coffee later  hot beverage
42   ham         hi teamthe server start worked check again
43   ham                   meeting at pm today dont be late
44   ham                   can u review my code its mess ll
45   ham  hey johnson u send the report by today ply tha...
46   ham                         thanks for or help earlier
47   ham                               lunch pm let me know
48  spam                          free vacation click here
49   ham                   project deadline moved to friday

In [ ]:
chatwords={
    "u":"you",
    "omg":"oh my god",
    "r":"are",
    "plzzz":"please",
    "ur":"you are",
    "ill":"I will"
}

In [ ]:
def correcting_chatwords(text):
    words=text.split()
    new_words=[]
    for word in words:
        if word in chatwords:
            new_words.append(chatwords[word])
        else:
            new_words.append(word)
    return " ".join(new_words)

In [ ]:
txt="omg how r u"
correcting_chatwords(txt)

'oh my god how are you'

In [ ]:
df["email_text"]=df["email_text"].apply(correcting_chatwords)

In [ ]:
df.head()

  label                                         email_text
0  spam                             hot deal buy followers
1   ham              hey think there is a type in the file
2  spam  congress you won 1000 click here now face scre...
3  spam                                         click fast
4   ham               dont forget to submit the assignment

In [ ]:
df1=pd.read_csv("/content/urdu_noisy_sentiment_dataset.csv")

In [ ]:
df1

                                     text sentiment
0          مجھے یہ پروڈکٹ بہت پسند آیا!!!  positive
1                       یہ بہت خراب ہے!!!  negative
2   <p>بہت اچھی سروس</p> دوبارہ خریدوں گا  positive
3               یہ سب سے برا تجربہ تھا!!!  negative
4          بہت زبردست!!! https://shop.com  positive
5                      پیسے ضائع ہوگئے!!!  negative
6                         میں بہت خوش ہوں  positive
7                    <div>برا تجربہ</div>  negative
8                  سب سے بہترین پروڈکٹ!!!  positive
9                       میں بہت مایوس ہوں  negative
10                        واہ!!! بہت اچھا  positive
11               ایک دن میں خراب ہوگیا!!!  negative
12                   <b>مجھے پسند آیا</b>  positive
13                     بہت ہی خراب پروڈکٹ  negative
14                        فاسٹ ڈیلیوری!!!  positive
15                    ڈیلیوری بہت لیٹ تھی  negative
16                          مجھے اچھا لگا  positive
17           ٹھیک ہے لیکن زیادہ اچھا نہیں  negative
18              <html>بہت اچھا ڈیل</html>  positive
19                  براہ کرم ریفنڈ دیں!!!  negative
20                         عمدہ کوالٹی!!!  positive
21                       خراب کسٹمر سپورٹ  negative
22                            بہت اچھا!!!  positive
23                     قیمت کے مطابق نہیں  negative
24             میں ضرور recommend کروں گا  positive
25                     کام کرنا بند ہوگیا  negative
26               <span>اچھا پروڈکٹ</span>  positive
27                             بہت برا!!!  negative
28    دوبارہ آرڈر کروں گا https://buy.com  positive
29                           ٹوٹا ہوا ملا  negative
30                       بہت ہی زبردست!!!  positive
31                            سستی کوالٹی  negative
32                     مجھے بہت خوشی ہوئی  positive
33                            بہت خراب!!!  negative
34                        <h1>پرفیکٹ</h1>  positive
35                 باکس میں آئٹم نہیں تھا  negative
36                   بہت اچھا کام کرتا ہے  positive
37                    بہت برا سمیل آتا ہے  negative
38                          میں مطمئن ہوں  positive
39                      پیسے ضائع مت کریں  negative
40                              لاجواب!!!  positive
41                         بہت سلو رسپانس  negative
42                قیمت کے لحاظ سے اچھا ہے  positive
43                        پیکجنگ خراب تھی  negative
44             مجھے استعمال کرنا پسند آیا  positive
45                       بہت برا تجربہ!!!  negative
46                         اچھی سپورٹ ٹیم  positive
47                        اسٹاف بدتمیز ہے  negative
48                         بہت خوبصورت!!!  positive
49             میں recommend نہیں کروں گا  negative

In [ ]:
text_col = "text"      # Urdu sentence
label_col = "sentiment"   # sentiment (positive/negative)

In [ ]:
df1[label_col] = df1[label_col].str.lower()

# Example mapping
df1[label_col] = df1[label_col].map({
    "positive": 1,
    "negative": 0
})

In [ ]:
print(df1.head())
print(df1.isnull().sum())
print(df1[label_col].value_counts())

In [ ]:
def clean_urdu_text(text):
    text = text.lower()

    # Remove URLs
    text = re.sub(r'http\S+|www\S+', '', text)

    # Remove emails
    text = re.sub(r'\S+@\S+', '', text)

    # Remove English words (optional)
    text = re.sub(r'[a-zA-Z]', '', text)

    # Remove numbers
    text = re.sub(r'\d+', '', text)

    # Remove punctuation
    text = re.sub(r'[^\w\s\u0600-\u06FF]', '', text)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [ ]:
df1[text_col] = df1[text_col].apply(clean_urdu_text)

In [ ]:
df1.head()

                             text sentiment  label
0        مجھے پروڈکٹ بہت پسند آیا  positive    NaN
1                        بہت خراب  negative    NaN
2  بہت اچھی سروس دوبارہ خریدوں گا  positive    NaN
3                سب برا تجربہ تھا  negative    NaN
4                      بہت زبردست  positive    NaN

In [ ]:
df1

                              text sentiment
0      مجھے یہ پروڈکٹ بہت پسند آیا  positive
1                   یہ بہت خراب ہے  negative
2   بہت اچھی سروس دوبارہ خریدوں گا  positive
3           یہ سب سے برا تجربہ تھا  negative
4                       بہت زبردست  positive
5                  پیسے ضائع ہوگئے  negative
6                  میں بہت خوش ہوں  positive
7                        برا تجربہ  negative
8              سب سے بہترین پروڈکٹ  positive
9                میں بہت مایوس ہوں  negative
10                    واہ بہت اچھا  positive
11           ایک دن میں خراب ہوگیا  negative
12                   مجھے پسند آیا  positive
13              بہت ہی خراب پروڈکٹ  negative
14                    فاسٹ ڈیلیوری  positive
15             ڈیلیوری بہت لیٹ تھی  negative
16                   مجھے اچھا لگا  positive
17    ٹھیک ہے لیکن زیادہ اچھا نہیں  negative
18                    بہت اچھا ڈیل  positive
19              براہ کرم ریفنڈ دیں  negative
20                     عمدہ کوالٹی  positive
21                خراب کسٹمر سپورٹ  negative
22                        بہت اچھا  positive
23              قیمت کے مطابق نہیں  negative
24                میں ضرور کروں گا  positive
25              کام کرنا بند ہوگیا  negative
26                     اچھا پروڈکٹ  positive
27                         بہت برا  negative
28             دوبارہ آرڈر کروں گا  positive
29                    ٹوٹا ہوا ملا  negative
30                   بہت ہی زبردست  positive
31                     سستی کوالٹی  negative
32              مجھے بہت خوشی ہوئی  positive
33                        بہت خراب  negative
34                          پرفیکٹ  positive
35          باکس میں آئٹم نہیں تھا  negative
36            بہت اچھا کام کرتا ہے  positive
37             بہت برا سمیل آتا ہے  negative
38                   میں مطمئن ہوں  positive
39               پیسے ضائع مت کریں  negative
40                          لاجواب  positive
41                  بہت سلو رسپانس  negative
42         قیمت کے لحاظ سے اچھا ہے  positive
43                 پیکجنگ خراب تھی  negative
44      مجھے استعمال کرنا پسند آیا  positive
45                   بہت برا تجربہ  negative
46                  اچھی سپورٹ ٹیم  positive
47                 اسٹاف بدتمیز ہے  negative
48                     بہت خوبصورت  positive
49                میں نہیں کروں گا  negative

In [ ]:
urdu_stopwords = [
    "ہے", "ہیں", "کو", "میں", "کا", "کی", "کے", "اور",
    "سے", "پر", "یہ", "وہ", "کہ", "کر", "ہی"
]

def remove_stopwords(text):
    words = text.split()
    words = [w for w in words if w not in urdu_stopwords]
    return " ".join(words)

In [ ]:
df1[text_col] = df1[text_col].apply(remove_stopwords)

In [ ]:
df1[label_col] = df1[label_col].str.lower()

# Example mapping
df1[label_col] = df1[label_col].map({
    "positive": 1,
    "negative": 0
})

In [ ]:
df1 = df1.drop_duplicates(subset=[text_col])

In [ ]:
print(df1.head())
print(df1.isnull().sum())
print(df1[label_col].value_counts())

                             text sentiment  label
0        مجھے پروڈکٹ بہت پسند آیا  positive    NaN
1                        بہت خراب  negative    NaN
2  بہت اچھی سروس دوبارہ خریدوں گا  positive    NaN
3                سب برا تجربہ تھا  negative    NaN
4                      بہت زبردست  positive    NaN
text          0
sentiment     0
label        48
dtype: int64
Series([], Name: count, dtype: int64)

In [ ]:
df1.to_csv("cleaned_urdu_sentiment.csv", index=False)

In [ ]:
def normalize_urdu(text):
    text = re.sub(r'ي', 'ی', text)
    text = re.sub(r'ك', 'ک', text)
    text = re.sub(r'ة', 'ہ', text)
    return text

df1[text_col] = df1[text_col].apply(normalize_urdu)

/tmp/ipykernel_9576/1663366524.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[text_col] = df1[text_col].apply(normalize_urdu)

In [ ]:
df1

                              text sentiment  label
0         مجھے پروڈکٹ بہت پسند آیا  positive    NaN
1                         بہت خراب  negative    NaN
2   بہت اچھی سروس دوبارہ خریدوں گا  positive    NaN
3                 سب برا تجربہ تھا  negative    NaN
4                       بہت زبردست  positive    NaN
5                  پیسے ضائع ہوگئے  negative    NaN
6                      بہت خوش ہوں  positive    NaN
7                        برا تجربہ  negative    NaN
8                 سب بہترین پروڈکٹ  positive    NaN
9                    بہت مایوس ہوں  negative    NaN
10                    واہ بہت اچھا  positive    NaN
11               ایک دن خراب ہوگیا  negative    NaN
12                   مجھے پسند آیا  positive    NaN
13                 بہت خراب پروڈکٹ  negative    NaN
14                    فاسٹ ڈیلیوری  positive    NaN
15             ڈیلیوری بہت لیٹ تھی  negative    NaN
16                   مجھے اچھا لگا  positive    NaN
17       ٹھیک لیکن زیادہ اچھا نہیں  negative    NaN
18                    بہت اچھا ڈیل  positive    NaN
19              براہ کرم ریفنڈ دیں  negative    NaN
20                     عمدہ کوالٹی  positive    NaN
21                خراب کسٹمر سپورٹ  negative    NaN
22                        بہت اچھا  positive    NaN
23                 قیمت مطابق نہیں  negative    NaN
24                    ضرور کروں گا  positive    NaN
25              کام کرنا بند ہوگیا  negative    NaN
26                     اچھا پروڈکٹ  positive    NaN
27                         بہت برا  negative    NaN
28             دوبارہ آرڈر کروں گا  positive    NaN
29                    ٹوٹا ہوا ملا  negative    NaN
31                     سستی کوالٹی  negative    NaN
32              مجھے بہت خوشی ہوئی  positive    NaN
34                          پرفیکٹ  positive    NaN
35              باکس آئٹم نہیں تھا  negative    NaN
36               بہت اچھا کام کرتا  positive    NaN
37                بہت برا سمیل آتا  negative    NaN
38                       مطمئن ہوں  positive    NaN
39               پیسے ضائع مت کریں  negative    NaN
40                          لاجواب  positive    NaN
41                  بہت سلو رسپانس  negative    NaN
42                  قیمت لحاظ اچھا  positive    NaN
43                 پیکجنگ خراب تھی  negative    NaN
44      مجھے استعمال کرنا پسند آیا  positive    NaN
45                   بہت برا تجربہ  negative    NaN
46                  اچھی سپورٹ ٹیم  positive    NaN
47                    اسٹاف بدتمیز  negative    NaN
48                     بہت خوبصورت  positive    NaN
49                    نہیں کروں گا  negative    NaN

In [ ]:
df2=pd.read_csv("/content/marathi_noisy_sentiment.csv")

In [ ]:
df2

                                 text sentiment
0        मला हा प्रोडक्ट खूप आवडला!!!  positive
1                  हे खूप वाईट आहे!!!  negative
2     <p>खूप छान सेवा</p> पुन्हा घेईन  positive
3               सगळ्यात वाईट अनुभव!!!  negative
4       खूपच भारी!!! https://shop.com  positive
5                   पैसे वाया गेले!!!  negative
6                      मी खूप खुश आहे  positive
7               <div>खराब अनुभव</div>  negative
8            सर्वात बेस्ट प्रोडक्ट!!!  positive
9                      खूप निराश झालो  negative
10                      वा!!! खूप छान  positive
11                  १ दिवसात तुटलं!!!  negative
12                    <b>मस्त आहे</b>  positive
13                     भयंकर प्रोडक्ट  negative
14                 फास्ट डिलिव्हरी!!!  positive
15                      लेट डिलिव्हरी  negative
16                          मला आवडलं  positive
17         ठीक आहे पण फार चांगलं नाही  negative
18        <html>खूप चांगला डील</html>  positive
19                    रिफंड पाहिजे!!!  negative
20                  उत्तम क्वालिटी!!!  positive
21                 खराब कस्टमर सपोर्ट  negative
22                      खूप चांगलं!!!  positive
23                 किंमतीप्रमाणे नाही  negative
24            मी नक्की recommend करेन  positive
25                   काम करेनासं झालं  negative
26          <span>छान प्रोडक्ट</span>  positive
27                        फार वाईट!!!  negative
28  पुन्हा ऑर्डर करेन https://buy.com  positive
29                        तुटलेलं आलं  negative
30                     खूपच चांगलं!!!  positive
31                    स्वस्त क्वालिटी  negative
32                      खूप आनंद झाला  positive
33                        फार खराब!!!  negative
34                   <h1>परफेक्ट</h1>  positive
35             बॉक्समध्ये आयटम नव्हता  negative
36                   खूप छान काम करतं  positive
37                      वाईट वास येतो  negative
38                     मी समाधानी आहे  positive
39                पैसे वाया घालवू नका  negative
40                         अप्रतिम!!!  positive
41                     स्लो रिस्पॉन्स  negative
42                     पैशासाठी योग्य  positive
43                      पॅकेजिंग खराब  negative
44                 मला वापरायला आवडलं  positive
45                     भयंकर अनुभव!!!  negative
46                     छान सपोर्ट टीम  positive
47                     स्टाफ रude आहे  negative
48                       खूप सुंदर!!!  positive
49            मी recommend करणार नाही  negative

In [ ]:
text_col = "text"
label_col = "label"

In [ ]:
df2 = df2.dropna(subset=[text_col])
df2[text_col] = df2[text_col].astype(str)

In [ ]:
def clean_marathi_text(text):
    text = text.lower()

    # Remove URLs
    text = re.sub(r'http\S+|www\S+', '', text)

    # Remove emails
    text = re.sub(r'\S+@\S+', '', text)

    # Remove numbers
    text = re.sub(r'\d+', '', text)

    # Remove English characters (optional)
    text = re.sub(r'[a-zA-Z]', '', text)

    # Keep only Marathi (Devanagari Unicode range)
    text = re.sub(r'[^\u0900-\u097F\s]', '', text)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [ ]:
df2

                                 text sentiment
0        मला हा प्रोडक्ट खूप आवडला!!!  positive
1                  हे खूप वाईट आहे!!!  negative
2     <p>खूप छान सेवा</p> पुन्हा घेईन  positive
3               सगळ्यात वाईट अनुभव!!!  negative
4       खूपच भारी!!! https://shop.com  positive
5                   पैसे वाया गेले!!!  negative
6                      मी खूप खुश आहे  positive
7               <div>खराब अनुभव</div>  negative
8            सर्वात बेस्ट प्रोडक्ट!!!  positive
9                      खूप निराश झालो  negative
10                      वा!!! खूप छान  positive
11                  १ दिवसात तुटलं!!!  negative
12                    <b>मस्त आहे</b>  positive
13                     भयंकर प्रोडक्ट  negative
14                 फास्ट डिलिव्हरी!!!  positive
15                      लेट डिलिव्हरी  negative
16                          मला आवडलं  positive
17         ठीक आहे पण फार चांगलं नाही  negative
18        <html>खूप चांगला डील</html>  positive
19                    रिफंड पाहिजे!!!  negative
20                  उत्तम क्वालिटी!!!  positive
21                 खराब कस्टमर सपोर्ट  negative
22                      खूप चांगलं!!!  positive
23                 किंमतीप्रमाणे नाही  negative
24            मी नक्की recommend करेन  positive
25                   काम करेनासं झालं  negative
26          <span>छान प्रोडक्ट</span>  positive
27                        फार वाईट!!!  negative
28  पुन्हा ऑर्डर करेन https://buy.com  positive
29                        तुटलेलं आलं  negative
30                     खूपच चांगलं!!!  positive
31                    स्वस्त क्वालिटी  negative
32                      खूप आनंद झाला  positive
33                        फार खराब!!!  negative
34                   <h1>परफेक्ट</h1>  positive
35             बॉक्समध्ये आयटम नव्हता  negative
36                   खूप छान काम करतं  positive
37                      वाईट वास येतो  negative
38                     मी समाधानी आहे  positive
39                पैसे वाया घालवू नका  negative
40                         अप्रतिम!!!  positive
41                     स्लो रिस्पॉन्स  negative
42                     पैशासाठी योग्य  positive
43                      पॅकेजिंग खराब  negative
44                 मला वापरायला आवडलं  positive
45                     भयंकर अनुभव!!!  negative
46                     छान सपोर्ट टीम  positive
47                     स्टाफ रude आहे  negative
48                       खूप सुंदर!!!  positive
49            मी recommend करणार नाही  negative

In [ ]:
df2[text_col] = df2[text_col].apply(clean_marathi_text)

In [ ]:
marathi_stopwords = [
    "आहे", "आहेत", "मी", "तू", "तो", "ती", "ते",
    "आणि", "किंवा", "पण", "म्हणून", "वर", "मध्ये",
    "का", "हो", "नाही", "होते", "होता"
]

def remove_stopwords(text):
    words = text.split()
    words = [w for w in words if w not in marathi_stopwords]
    return " ".join(words)

df2[text_col] = df2[text_col].apply(remove_stopwords)

In [ ]:
def normalize_marathi(text):
    text = re.sub(r'क़', 'क', text)
    text = re.sub(r'ख़', 'ख', text)
    text = re.sub(r'ग़', 'ग', text)
    text = re.sub(r'ज़', 'ज', text)
    text = re.sub(r'फ़', 'फ', text)
    return text

df2[text_col] = df2[text_col].apply(normalize_marathi)

In [ ]:
label_col = "sentiment" # Update label_col for df2
df2[label_col] = df2[label_col].str.lower()

df2[label_col] = df2[label_col].map({
    "positive": 1,
    "negative": 0,
    "neutral": 2   # if exists
})

In [ ]:
df2 = df2.drop_duplicates(subset=[text_col])

In [ ]:
print(df2.head())
print(df2.isnull().sum())
print(df2[label_col].value_counts())

                        text  sentiment
0  मला हा प्रोडक्ट खूप आवडला          1
1                हे खूप वाईट          0
2   खूप छान सेवा पुन्हा घेईन          1
3         सगळ्यात वाईट अनुभव          0
4                  खूपच भारी          1
text         0
sentiment    0
dtype: int64
sentiment
1    25
0    25
Name: count, dtype: int64

In [ ]:
df2.to_csv("cleaned_marathi_sentiment.csv", index=False)

In [ ]:
df2

                         text  sentiment
0   मला हा प्रोडक्ट खूप आवडला          1
1                 हे खूप वाईट          0
2    खूप छान सेवा पुन्हा घेईन          1
3          सगळ्यात वाईट अनुभव          0
4                   खूपच भारी          1
5              पैसे वाया गेले          0
6                     खूप खुश          1
7                  खराब अनुभव          0
8       सर्वात बेस्ट प्रोडक्ट          1
9              खूप निराश झालो          0
10                 वा खूप छान          1
11               दिवसात तुटलं          0
12                       मस्त          1
13             भयंकर प्रोडक्ट          0
14            फास्ट डिलिव्हरी          1
15              लेट डिलिव्हरी          0
16                  मला आवडलं          1
17             ठीक फार चांगलं          0
18             खूप चांगला डील          1
19               रिफंड पाहिजे          0
20             उत्तम क्वालिटी          1
21         खराब कस्टमर सपोर्ट          0
22                 खूप चांगलं          1
23              किंमतीप्रमाणे          0
24                 नक्की करेन          1
25           काम करेनासं झालं          0
26               छान प्रोडक्ट          1
27                   फार वाईट          0
28          पुन्हा ऑर्डर करेन          1
29                तुटलेलं आलं          0
30                खूपच चांगलं          1
31            स्वस्त क्वालिटी          0
32              खूप आनंद झाला          1
33                   फार खराब          0
34                    परफेक्ट          1
35     बॉक्समध्ये आयटम नव्हता          0
36           खूप छान काम करतं          1
37              वाईट वास येतो          0
38                    समाधानी          1
39        पैसे वाया घालवू नका          0
40                    अप्रतिम          1
41             स्लो रिस्पॉन्स          0
42             पैशासाठी योग्य          1
43              पॅकेजिंग खराब          0
44         मला वापरायला आवडलं          1
45                भयंकर अनुभव          0
46             छान सपोर्ट टीम          1
47                    स्टाफ र          0
48                  खूप सुंदर          1
49                      करणार          0